### PR TITLE
XPathEval

### PR DESCRIPTION
**Pull request by nc9**
* Implemented checkConstraint
 * Tests for simple evaluation pass
 * Date tests pass

### CODE REVIEW

**Review by chienleng — COMMENTED** [review]
thanks, looks good to me. And simple enough to use.

**Comment by chienleng** [comment]
Do you want me to merge or is there more work to be done for this branch?

**Comment by nc9** [comment]
I just finished checkRelevant so both the constraints and show/hide should work if you wire them up - check the unit tests

**Comment by nc9** [comment]
The relevancy tests are a bit more complicated because of the expression operators like `or` and `and` but we're not doing anything super complicated so it should work.

**Comment by nc9** [comment]
It's probably best to pass an object to use checkRelevancy rather than a DOM node or just a string -

ie.

```js
const state = {
  "tested": "yes_tested"
}

assert(checkRelevancy(state, "${tested} = 'yes_tested'") === true)
```

**Comment by nc9** [comment]
btw i'll add `yarn test` to the CI pipeline and we can write some more around the survey and eventually add selenium

**Pull request merged**
